config/routes.rb
Rails.application.routes.draw do
  
  resources :customers, only: [:index, :show, :update, :create] do
    collection do
      get :search
    end
  end

  devise_for :users #, :controllers => { :registrations => "user/registrations" }
  get 'home/index'

  root to: 'home#index'

end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :customers
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	belongs_to :city
	belongs_to :customers_type

	def self.search(params)
		#@customers = Customer.find(:all, :conditions => conditions(params))
		if params
			query = params.clone
			query.map do |k,v| 
				#puts("k=" + k)
				query[k] = ((k == 'city_id' || v.blank?) ? v : ("%#{v}%"))
			end
			where((query.map { |f| f[0].to_s + " LIKE :" + f[0].to_s unless f[1].blank? }).reject(&:blank?).join(' AND '), query).order(:lname)
			# (f[0].to_s == "city_id" ? " = :" : " LIKE :")
			#(("%#{v}%") unless (k == :city_id || v.blank?))||v
	  else
	    scoped
	  end
	end

end

app/models/customers_type.rb
class CustomersType < ActiveRecord::Base
	has_many :customers
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]

  belongs_to :role

  def admin?
  	role_id == 1
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :email
    devise_parameter_sanitizer.for(:sign_up) << :fname
    devise_parameter_sanitizer.for(:sign_up) << :lname

    #{ |u| u.permit(:fname, :lname, :email) }
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  respond_to :html, :js

  before_filter :set_active_tab
	def set_active_tab
	  @active_tab = 2
	end

  def index
  	flash[:warning] = nil
  	@customer = Customer.new

  	if params[:from_page]
  		@customer = Customer.new(customer_params)
  	end
  end

  def search
  	flash[:warning] = nil
		res = Customer.search(params[:customer])
		c = res.count
		if c == 0
			render :json => res
		elsif c == 1
			@customer = res.first
			render :json => [{ redirect_url: customer_url(@customer) }]
		else
			a=[]
			res.map { |p| a.push p[:city_id]}
			cities = City.where("id in (?)",a)
      render :json => {res: res, nested: cities}
		end
  end

  def show
  	@customer = Customer.find(params[:id])
  end

  def update
  	@customer = Customer.find(params[:id])
  	flash[:notice] = nil
  	flash[:error] = nil
    if @customer.update_attributes(customer_params)
      flash[:notice] = "true"
      redirect_to @customer
    else
      flash[:error] = "true"
      render :show
		end
  end

  def create
  		@customer = Customer.new(customer_params)
  	if params[:search]
  		#redirect_to customers_search_path(customer: @customer.attributes)
		
		else
	    if @customer.save
	      redirect_to @customer
	    else
	      flash[:error] = "true"
	      render :index
	    end
		end
  end

  private

  def customer_params
    params.require(:customer).permit(:fname, :lname, :tz, :gender, :city_id, :address, :zipcode, :phone, :email, :customers_type_id, :notes)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :set_active_tab
	def set_active_tab
	  @active_tab = 1
	end

  def index
  	@customer = Customer.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/customer/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="panel">
    
    <div class="row">
      <div class="large-12 columns">
        <h2>איתור והוספת לקוח</h2>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <p>&nbsp;</p>
      </div>
    </div>
		
		<% if flash[:warning] %>
		<div class="row">
      <div class="large-12 columns">
        <div class="panel radius warning">
        	<p>לא נמצאו לקוחות העונים לפרטים שהוזנו</p>
        </div>
      </div>
    </div>
    <% end %>

    <%= form_for @customer, url: {action: "create"} do |f| %>
      <div class="row">
        <div class="medium-4 columns">
          <label for="">שם פרטי
            <%= f.text_field(:fname) %>
          </label>
        </div>
        
        <div class="medium-4 columns">
          <label for="">שם משפחה
            <%= f.text_field(:lname) %>
          </label>
        </div>
        
        <div class="medium-2 columns">
          <label for="">ת.ז.
            <%= f.text_field(:tz) %>
          </label>
        </div>
        
        <div class="medium-2 columns">
          <label for="">מגדר
            <%= select(:customer, :gender, [['זכר', 'זכר'], ['נקבה', 'נקבה']], {include_blank: true}) %>
          </label>
        </div>

        <div class="medium-0 columns">
        </div>
      </div>
      
      <div class="row">
        <div class="medium-4 columns">
          <label for="">ישוב
            <%= collection_select(:customer, :city_id, City.all.order('name'), :id, :name, {include_blank: true}) %>
          </label>
        </div>
        <div class="medium-4 columns">
          <label for="">כתובת
            <%= f.text_field(:address) %>
          </label>
        </div>
        <div class="medium-2 columns">
          <label for="">מיקוד
            <%= f.text_field(:zipcode) %>
          </label>
        </div>

        <div class="medium-2 columns">
        </div>
      </div>

      <div class="row">
        <div class="medium-4 columns">
          <label for="">טלפון
            <%= f.telephone_field(:phone) %>
          </label>
        </div>
        
        <div class="medium-6 columns">
          <label for="">דוא"ל
            <%= f.email_field(:email) %>
          </label>
        </div>

        <div class="medium-2 columns">
        </div>
      </div>

      <div class="row">
        <div class="large-12 columns">&nbsp;</div>
      </div>

      <div class="row">
        <div class="large-12 columns">
          <div class="left">
            <%= submit_tag "איתור לקוח קיים", name: 'search', :id=>"btn_search", :class=>"button small radius" %>
            <%= submit_tag "הוספת לקוח חדש", :id=>"btn_new", :class=>"button small radius" %>
          </div>
        </div>
      </div>
    <% end %>

    </div>
  </div>
</div>

<div id="cSelectModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <h2 id="modalTitle">בחירת לקוח</h2>
  <p class="lead">נמצאו מספר לקוחות עם הפרטים שהזנת</p>
  <div>
    <table id="cResultList">
      <tr>
        <th>תז</th>
        <th>שם פרטי</th>
        <th>שם משפחה</th>
        <th>מגדר</th>
        <th>ישוב</th>
        <th>כתובת</th>
        <th>טלפון</th>
        <th>דוא"ל</th>
      </tr>
      <tr>
        <td>111111111</td>
        <td>אלון</td>
        <td>פנחס</td>
        <td>ז</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>222222222</td>
        <td>אלון</td>
        <td>צוקר</td>
        <td>ז</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>333333333</td>
        <td>אלון</td>
        <td>שיטרית</td>
        <td>ז</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </table>
  </div>
  <p></p>
  <div class="left">
    <a href="customer.html" class="button small radius">פתיחת כרטיס לקוח</a>
  </div>

  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<script type="text/javascript">
  // $("#findBtn").click(function(){
  //   $('#cSelectModal').foundation('reveal', 'open');
  // });
  // $("#cResultList tr:not(:first-child)").click(function(){
  //   $("#cResultList tr").removeClass("selected");
  //   $(this).addClass("selected");
  // });

  
</script>

app/views/customers/_results.html.erb
<div id="cSelectModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <h2 id="modalTitle">בחירת לקוח</h2>
  <p class="lead">נמצאו <span id="res_count">0</span> לקוחות עם הפרטים שהזנת</p>
  <div id="tableContainer">
  </div>
  <p></p>
  <div class="left">
    <%= link_to 'פתיחת כרטיס לקוח', '', {:id=>'btn_select', :class=>"button small radius secondary disabled"} %>
  </div>

  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<script type="text/javascript">

</script>

app/views/customers/edit.html.erb
<h1>Customer#edit</h1>
<p>Find me in app/views/customer/edit.html.erb</p>

app/views/customers/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="panel">
    
    <div class="row">
      <div class="large-12 columns">
        <h2>איתור והוספת לקוח</h2>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <p>&nbsp;</p>
      </div>
    </div>
    
    <div class="row hide" id="no_result">
      <div class="large-12 columns">
        <div class="panel radius warning">
          <p>לא נמצאו לקוחות העונים לפרטים שהוזנו</p>
        </div>
      </div>
    </div>

    <%= form_for @customer do |f| %>
      <div class="row">
        <div class="medium-3 columns">
          <label for="">שם פרטי
            <%= f.text_field(:fname) %>
          </label>
        </div>
        
        <div class="medium-4 columns">
          <label for="">שם משפחה
            <%= f.text_field(:lname) %>
          </label>
        </div>
        
        <div class="medium-2 columns">
          <label for="">ת.ז.
            <%= f.text_field(:tz) %>
          </label>
        </div>
        
        <div class="medium-2 columns">
          <label for="">מגדר
            <%= select(:customer, :gender, [['זכר', 'זכר'], ['נקבה', 'נקבה']], {include_blank: true}) %>
          </label>
        </div>

        <div class="medium-1 columns">
        </div>
      </div>
      
      <div class="row">
        <div class="medium-3 columns">
          <label for="">ישוב
            <%= collection_select(:customer, :city_id, City.all.order('name'), :id, :name, {include_blank: true}) %>
          </label>
        </div>
        <div class="medium-6 columns">
          <label for="">כתובת
            <%= f.text_field(:address) %>
          </label>
        </div>
        <div class="medium-2 columns">
          <label for="">מיקוד
            <%= f.text_field(:zipcode) %>
          </label>
        </div>

        <div class="medium-0 columns">
        </div>
      </div>

      <div class="row">
        <div class="medium-3 columns">
          <label for="">טלפון
            <%= f.telephone_field(:phone) %>
          </label>
        </div>
        
        <div class="medium-6 columns">
          <label for="">דוא"ל
            <%= f.email_field(:email) %>
          </label>
        </div>

        <div class="medium-2 columns">
          
        </div>
      </div>

      <div class="row">
        <div class="large-12 columns"><p>&nbsp;</p></div>
      </div>

      
      <div class="row">
        <div class="large-12 columns">
          <div class="left">
            <%= submit_tag "איתור לקוח קיים", :id=>"btn_search", :class=>"button small radius" %>
            <%#= link_to "איתור לקוח קיים", customer_search_path(:customer => @customer.attributes), method: :get, :class=>"button small radius" %>
            <%= submit_tag "הוספת לקוח חדש", :id=>"btn_create", :class=>"button small radius" %>
          </div>
        </div>
      </div>
    <% end %>

    </div>
  </div>
</div>

<%=render 'results' %>

app/views/customers/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="panel">
        
      <div class="row">
        <div class="large-4 columns">
          <h2>כרטיס לקוח</h2><h2><small><%= @customer.fname.to_s + " " + @customer.lname.to_s %></small></h2>
        </div>
        <div class="large-8 columns">
          <div class="left" id="sub_toolbar">
            <%= link_to raw("<i class='fa fa-retweet'></i> החלפת לקוח"), customers_path, :class=>"button small radius" %>
            <!--a href="customers.html" class="button small radius"><i class="fa fa-retweet"></i> החלפת לקוח</a-->
            <a href="#" class="button small radius" id="btn_edit"><i class="fa fa-pencil-square-o"></i> עידכון פרטים</a>
            <a href="#" class="button small radius">השאלה</a>
            <a href="#" class="button small radius">מכירה</a>
          </div>
        </div>
      </div>

      <% if flash[:notice] %>
			<div class="row notice">
	      <div class="large-12 columns">
	        <div class="panel radius success">
	        	<p>העידכון נשמר בהצלחה</p>
	        </div>
	      </div>
	    </div>
	    <% end %>

      

      <%= form_for @customer, url: {action: "update"} do |f| %>
      <div class="row">
        <div class="medium-3 columns">
          <label for="">שם פרטי
            <%= f.text_field(:fname) %>
          </label>
        </div>
        
        <div class="medium-3 columns">
          <label for="">שם משפחה
            <%= f.text_field(:lname) %>
          </label>
        </div>
        
        <div class="medium-2 columns">
          <label for="">ת.ז.
            <%= f.text_field(:tz) %>
          </label>
        </div>
        
        <div class="medium-2 columns">
          <label for="">מגדר
          	<%= f.text_field(:gender, :class => "vmode") %>
            <%= select(:customer, :gender, [['זכר', 'זכר'], ['נקבה', 'נקבה']], {include_blank: true}, :class => "emode hide") %>
          </label>
        </div>

        <div class="medium-2 columns">
        </div>
      </div>
      
      <div class="row">
        <div class="medium-3 columns">
          <label for="">ישוב
            <%= fields_for @customer.city do |city_form| %>
					    <%= city_form.text_field :name, :class => "vmode" %>
					  <% end %>
            <%= collection_select(:customer, :city_id, City.all.order('name'), :id, :name, {include_blank: true}, :class => "emode hide") %>
          </label>
        </div>
        <div class="medium-5 columns">
          <label for="">כתובת
            <%= f.text_field(:address) %>
          </label>
        </div>
        <div class="medium-2 columns">
          <label for="">מיקוד
            <%= f.text_field(:zipcode) %>
          </label>
        </div>

        <div class="medium-2 columns">
        </div>
      </div>

      <div class="row">
        <div class="medium-3 columns">
          <label for="">טלפון
            <%= f.telephone_field(:phone) %>
          </label>
        </div>
        
        <div class="medium-5 columns">
          <label for="">דוא"ל
            <%= f.email_field(:email) %>
          </label>
        </div>

        <div class="medium-2 columns">
          <label for="">סוג לקוח
            <%= fields_for @customer.customers_type do |customers_type_form| %>
              <%= customers_type_form.text_field :name, :class => "vmode" %>
            <% end %>
            <%= collection_select(:customer, :customers_type_id, CustomersType.all.order('name'), :id, :name, {include_blank: true}, :class => "emode hide") %>
          </label>
        </div>

        <div class="medium-2 columns">
        </div>
      </div>

      <div class="row">
        <div class="large-10 columns">
          <label for="">הערות
            <%= f.email_field(:notes) %>
          </label>
        </div>
      </div>

      <div class="row">
        <div class="large-12 columns">&nbsp;</div>
      </div>

      <div id="editbuttons" class="row hide">
        <div class="large-12 columns text-left">
          <%= submit_tag "שמירה", :class=>"button small radius" %>
          <a href="" class="button small radius">ביטול</a>
        </div>
      </div>
      <% end %>

      <div class="row">
        <div class="large-12 columns">
          <div id="extradetails">
            <ul class="tabs" data-tab role="tablist">
              <li class="tab-title active" role="presentation"><a href="#panel2-1" role="tab" tabindex="0" aria-selected="true" aria-controls="panel2-1">השאלות</a></li>
              <li class="tab-title" role="presentation"><a href="#panel2-2" role="tab" tabindex="0" aria-selected="false" aria-controls="panel2-2">הסטוריית השאלות</a></li>
              <li class="tab-title" role="presentation"><a href="#panel2-3" role="tab" tabindex="0" aria-selected="false" aria-controls="panel2-3">הסטוריית רכישות</a></li>
              <li class="tab-title" role="presentation"><a href="#panel2-4" role="tab" tabindex="0" aria-selected="false" aria-controls="panel2-4">תשלומים</a></li>
            </ul>
            <div class="tabs-content">
              <section role="tabpanel" aria-hidden="false" class="content active" id="panel2-1">
                <table>
                  <tr>
                    <th>מק"ט</th>
                    <th>מוצר</th>
                    <th>פריט</th>
                    <th>תאריך השאלה</th>
                    <th>תאריך אחרון להחזרה</th>
                    <th>ימי איחור</th>
                    <th>החזרה</th>
                  </tr>
                  <tr>
                    <td>24568225</td>
                    <td>הליכון עם גלגלים</td>
                    <td>110</td>
                    <td>08/09/2015</td>
                    <td>07/11/2015</td>
                    <td>0</td>
                    <td class="text-center"><a href="#" class="button tiny radius">החזר</a></td>
                  </tr>
                </table>
              </section>
              <section role="tabpanel" aria-hidden="true" class="content" id="panel2-2">
                <table>
                  <tr>
                    <th>מק"ט</th>
                    <th>מוצר</th>
                    <th>פריט</th>
                    <th>תאריך השאלה</th>
                    <th>תאריך אחרון להחזרה</th>
                    <th>תאריך החזרה בפועל</th>
                    <th>ימי איחור</th>
                    <th>הערות</th>
                  </tr>
                  <tr>
                    <td>111222333</td>
                    <td>כיסה גלגלים ממונע</td>
                    <td>202</td>
                    <td>12/07/2015</td>
                    <td>11/10/2015</td>
                    <td>08/09/2015</td>
                    <td>0</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>111222333</td>
                    <td>כיסה גלגלים ממונע</td>
                    <td>202</td>
                    <td>12/04/2015</td>
                    <td>11/07/2015</td>
                    <td><font style="color: red">12/07/2015</font></td>
                    <td>1</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>111222333</td>
                    <td>כיסה גלגלים ממונע</td>
                    <td>202</td>
                    <td>12/07/2015</td>
                    <td>11/10/2015</td>
                    <td>08/09/2015</td>
                    <td>0</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>111222333</td>
                    <td>כיסה גלגלים ממונע</td>
                    <td>202</td>
                    <td>12/04/2015</td>
                    <td>11/07/2015</td>
                    <td><font style="color: red">12/07/2015</font></td>
                    <td>1</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>111222333</td>
                    <td>כיסה גלגלים ממונע</td>
                    <td>202</td>
                    <td>12/07/2015</td>
                    <td>11/10/2015</td>
                    <td>08/09/2015</td>
                    <td>0</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>111222333</td>
                    <td>כיסה גלגלים ממונע</td>
                    <td>202</td>
                    <td>12/04/2015</td>
                    <td>11/07/2015</td>
                    <td><font style="color: red">12/07/2015</font></td>
                    <td>1</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>111222333</td>
                    <td>כיסה גלגלים ממונע</td>
                    <td>202</td>
                    <td>12/07/2015</td>
                    <td>11/10/2015</td>
                    <td>08/09/2015</td>
                    <td>0</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>111222333</td>
                    <td>כיסה גלגלים ממונע</td>
                    <td>202</td>
                    <td>12/04/2015</td>
                    <td>11/07/2015</td>
                    <td><font style="color: red">12/07/2015</font></td>
                    <td>1</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>111222333</td>
                    <td>כיסה גלגלים ממונע</td>
                    <td>202</td>
                    <td>12/07/2015</td>
                    <td>11/10/2015</td>
                    <td>08/09/2015</td>
                    <td>0</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>111222333</td>
                    <td>כיסה גלגלים ממונע</td>
                    <td>202</td>
                    <td>12/04/2015</td>
                    <td>11/07/2015</td>
                    <td><font style="color: red">12/07/2015</font></td>
                    <td>1</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>111222333</td>
                    <td>כיסה גלגלים ממונע</td>
                    <td>202</td>
                    <td>12/07/2015</td>
                    <td>11/10/2015</td>
                    <td>08/09/2015</td>
                    <td>0</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>111222333</td>
                    <td>כיסה גלגלים ממונע</td>
                    <td>202</td>
                    <td>12/04/2015</td>
                    <td>11/07/2015</td>
                    <td><font style="color: red">12/07/2015</font></td>
                    <td>1</td>
                    <td></td>
                  </tr>
                </table>
              </section>
              <section role="tabpanel" aria-hidden="true" class="content" id="panel2-3">
                <h2>Third panel content goes here...</h2>
              </section>
              <section role="tabpanel" aria-hidden="true" class="content" id="panel2-4">
                <h2>Fourth panel content goes here...</h2>
              </section>
            </div>
          </div>
        </div>
      </div>
      
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $(function(){
      $("input").prop( "disabled", true );
    });

    $("#btn_edit").click(function(){
      $("input").prop( "disabled", false );
      $("#sub_toolbar>a").addClass("secondary disabled");
      $("#editbuttons").show();
      $(".row.notice").hide(200);
      $(".emode").show();
      $(".vmode").hide();
    });

    $("#editbuttons a").click(function(){
      $("input").prop( "disabled", true );
      $("#sub_toolbar>a").removeClass("secondary disabled");
      $("#editbuttons").hide();
      $(".emode").hide();
      $(".vmode").show();
    });

    $(".row.notice").ready(function(){
    	$(".row.notice").delay(4000).hide(400);
    });

  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>מועדון ליונס הוד השרון - <% if current_user %><%= current_user.fname + " " + current_user.lname %><% end %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application" %>
  <%#= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body dir="rtl">

	<div class="fixed">
  	<nav class="top-bar" data-topbar role="navigation" data-options="is_hover: false">
    	<ul class="title-area">
      	<li class="name">
        	<h1><a href="#"><%= image_tag "logo_small.png" %> מועדון ליונס הוד השרון</a></h1>
        </li>
      </ul>

      <section class="top-bar-section">
      	<ul class="right" data-active=<%= @active_tab %>>
        	<li><%= link_to 'הודעות והתראות', root_path %><!--a href="#">הודעות והתראות</a--></li>
          <li><%= link_to 'לקוחות', customers_path %><!--a href="customers.html">לקוחות</a--></li>
          <li><a href="#">ציוד ומלאי</a></li>
        </ul>

        <ul class="left">
        <% if current_user %>
          <li class="has-dropdown">
            <a href="#">
              <u>
                  <%= current_user.fname + " " + current_user.lname %>
              </u>
            </a>
            <ul class="dropdown">
              <li><a href="#">הגדרות</a></li>
              <li> <%= link_to "יציאה", destroy_user_session_path, method: :delete %><!--a href="#">התנתק</a--></li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to "כניסה למערכת", new_user_session_path %>
          </li>
        <% end %>
        </ul>
      </section>
    </nav>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <p>&nbsp;</p>
    </div>
  </div>

	<%= yield %>

</body>
</html>